/*
 * This source file was generated by the Gradle 'init' task
 */
package org.dsa;

import org.dsa.datastructures.BTree.BTreeIterative;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        BTreeIterative tree = new BTreeIterative(2);

        // Insert
        int[] keys = {10, 20, 30, 40, 50, 25, 35, 5, 1, 3};
        for (int k : keys) {
            tree.insert(k);
            System.out.println("Inserted " + k);
            System.out.println();
        }

        // Search existing
        int[] shouldFind = {10, 30, 50, 25, 35, 1, 3};
        for (int k : shouldFind) {
            System.out.println("Search " + k + ": " + (tree.search(k) ? "PASS" : "FAIL (expected true)"));
        }

        // Search missing
        int[] shouldMiss = {15, 99, 7};
        for (int k : shouldMiss) {
            System.out.println("Search " + k + ": " + (!tree.search(k) ? "PASS" : "FAIL (expected false)"));
        }

        // Duplicate
        System.out.println("Duplicate 10: " + (tree.insert(10) ? "PASS" : "FAIL"));
    }
}
